version: '3.5'

services:

    chem_kit_api:
        build:
          context: ./
          dockerfile: ./Dockerfile
        image: yannbeauxis/chem-kit-api:0.1.1
        container_name: "chem_kit_api"
        environment:
            - PORT=8000
        working_dir: /opt/chem_kit_api
        stdin_open: true
        tty: true
        ports: 
            - "8000:8000"
        user: root
        # command: bash
        # command: uvicorn main:app --host 0.0.0.0 --port 80 # bash # /usr/local/bin/uwsgi /etc/uwsgi/uwsgi.ini
        # command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000

    docker_hoster:
        # To be able to access to docker containers names in dns resolution.
        image: dvdarias/docker-hoster
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - /etc/hosts:/tmp/hosts
                                            